# Generated by Django 3.1.2 on 2020-11-11 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Especificaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procesador', models.CharField(max_length=30)),
                ('velocidadProc', models.CharField(max_length=30)),
                ('cantNucleo', models.CharField(max_length=30)),
                ('ram', models.CharField(max_length=30)),
                ('expandibleRAM', models.CharField(max_length=30)),
                ('almacenamiento', models.CharField(max_length=30)),
                ('pantalla', models.CharField(max_length=30)),
                ('resolucion', models.CharField(max_length=30)),
                ('tarjetaVideo', models.CharField(max_length=30)),
                ('modeloTarjeta', models.CharField(max_length=30)),
                ('usb', models.CharField(max_length=30)),
                ('hdmi', models.CharField(max_length=30)),
                ('sistOperativo', models.CharField(max_length=30)),
                ('bateria', models.CharField(max_length=50)),
            ],
        ),
    ]
