# Generated by Django 3.1 on 2020-11-11 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='especificaciones',
            name='imagen',
            field=models.ImageField(null=True, upload_to='especificaciones'),
        ),
    ]
