# Generated by Django 3.1 on 2020-11-11 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_especificaciones_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Televisores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=15)),
                ('tamanio', models.CharField(max_length=15)),
                ('resolucion', models.CharField(max_length=40)),
                ('smarttv', models.CharField(max_length=15)),
                ('tasarefresco', models.CharField(max_length=15)),
                ('usb', models.CharField(max_length=15)),
                ('hdmi', models.CharField(max_length=15)),
            ],
        ),
    ]
