# Generated by Django 3.1 on 2020-11-11 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_especificaciones_recomendacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='especificaciones',
            old_name='imagen',
            new_name='imagena',
        ),
        migrations.AddField(
            model_name='especificaciones',
            name='imagenb',
            field=models.ImageField(null=True, upload_to='especificaciones'),
        ),
        migrations.AddField(
            model_name='especificaciones',
            name='imagenc',
            field=models.ImageField(null=True, upload_to='especificaciones'),
        ),
        migrations.AddField(
            model_name='especificaciones',
            name='nombre',
            field=models.CharField(default="", max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='televisores',
            name='imagena',
            field=models.ImageField(null=True, upload_to='especificaciones'),
        ),
        migrations.AddField(
            model_name='televisores',
            name='imagenb',
            field=models.ImageField(null=True, upload_to='especificaciones'),
        ),
        migrations.AddField(
            model_name='televisores',
            name='imagenc',
            field=models.ImageField(null=True, upload_to='especificaciones'),
        ),
        migrations.AddField(
            model_name='televisores',
            name='nombre',
            field=models.CharField(default="", max_length=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='televisores',
            name='smarttv',
            field=models.BooleanField(),
        ),
    ]
