# Generated by Django 3.1 on 2020-11-11 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_auto_20201111_0300'),
    ]

    operations = [
        migrations.CreateModel(
            name='Celulares',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('tipopantalla', models.CharField(max_length=30)),
                ('tamaño', models.CharField(max_length=30)),
                ('ram', models.CharField(max_length=30)),
                ('memoriainterna', models.CharField(max_length=30)),
                ('sistemaoperativo', models.CharField(max_length=30)),
                ('camaraprincipal', models.CharField(max_length=30)),
                ('camarafrontal', models.CharField(max_length=30)),
                ('imagena', models.ImageField(null=True, upload_to='celulares')),
                ('imagenb', models.ImageField(null=True, upload_to='celulares')),
                ('imagenc', models.ImageField(null=True, upload_to='celulares')),
            ],
        ),
        migrations.CreateModel(
            name='Notebooks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('procesador', models.CharField(max_length=30)),
                ('velocidadProc', models.CharField(max_length=30)),
                ('cantNucleo', models.CharField(max_length=30)),
                ('ram', models.CharField(max_length=30)),
                ('expandibleRAM', models.CharField(max_length=30)),
                ('almacenamiento', models.CharField(max_length=30)),
                ('pantalla', models.CharField(max_length=30)),
                ('resolucion', models.CharField(max_length=30)),
                ('tarjetaVideo', models.CharField(max_length=30)),
                ('modeloTarjeta', models.CharField(max_length=30)),
                ('usb', models.CharField(max_length=30)),
                ('hdmi', models.CharField(max_length=30)),
                ('sistOperativo', models.CharField(max_length=30)),
                ('bateria', models.CharField(max_length=50)),
                ('recomendacion', models.TextField()),
                ('imagena', models.ImageField(null=True, upload_to='notebooks')),
                ('imagenb', models.ImageField(null=True, upload_to='notebooks')),
                ('imagenc', models.ImageField(null=True, upload_to='notebooks')),
            ],
        ),
        migrations.DeleteModel(
            name='Especificaciones',
        ),
        migrations.AlterField(
            model_name='televisores',
            name='imagena',
            field=models.ImageField(null=True, upload_to='televisores'),
        ),
        migrations.AlterField(
            model_name='televisores',
            name='imagenb',
            field=models.ImageField(null=True, upload_to='televisores'),
        ),
        migrations.AlterField(
            model_name='televisores',
            name='imagenc',
            field=models.ImageField(null=True, upload_to='televisores'),
        ),
    ]
