# Generated by Django 3.1.2 on 2020-11-12 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0006_auto_20201111_1701'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('categoria', models.CharField(max_length=30)),
                ('marca', models.CharField(max_length=30)),
                ('imagen', models.ImageField(null=True, upload_to='celulares')),
            ],
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Celulares',
        ),
        migrations.DeleteModel(
            name='Notebooks',
        ),
        migrations.DeleteModel(
            name='Televisores',
        ),
    ]
