# Generated by Django 3.1.2 on 2020-11-12 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0007_auto_20201112_0122'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Producto',
            new_name='Productos',
        ),
    ]
