# Generated by Django 3.1.2 on 2020-11-12 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0008_auto_20201112_0157'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Productos',
            new_name='Producto',
        ),
    ]
