# Generated by Django 3.1.2 on 2020-11-12 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0010_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
