# Generated by Django 3.1.2 on 2020-11-25 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0012_contacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='especificaciones',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagenb',
            field=models.ImageField(null=True, upload_to='celulares'),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagenc',
            field=models.ImageField(null=True, upload_to='celulares'),
        ),
        migrations.AddField(
            model_name='producto',
            name='recomendacion',
            field=models.TextField(null=True),
        ),
    ]
