# Generated by Django 3.1.2 on 2020-12-10 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0013_auto_20201124_2105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='especificaciones',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='imagenb',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='imagenc',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='recomendacion',
        ),
    ]
